apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: hhtpd
        image: httpd:2.4.46-alpine
        volumeMounts:
        - name: web
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: web
        hostPath: 
          path: /web
          type: Directory
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - ds
            topologyKey: kubernetes.io/hostname